image: node:latest

build:
  script:
    - apt update -y -qq
    - apt install zip -y -qq
    - ./configure
    - make

lint:
  before_script:
    - npm install -g eslint
  script:
    - ./configure
    - make eslint

check:
  script:
    - ./configure
    - make check

test:
  before_script:
    - export TBPROFILE="$(pwd)/tb-test-profile"
    - apt update -y -qq
    - apt install thunderbird gnupg2 zip unzip xvfb libgtk-3-0 -y -qq
    - which thunderbird
    - mkdir -p $TBPROFILE/extensions tmp jsunit
    - printf '%s/build/dist/' "$(pwd)" > "$TBPROFILE/extensions/{847b3a00-7ab1-11d4-8f02-006008948af5}"
    - printf '%s/jsunit/' "$(pwd)" > "$TBPROFILE/extensions/jsunit@enigmail.net"
    - printf 'user_pref("extensions.autoDisableScopes", 14);\n' > "$TBPROFILE/prefs.js"
    - printf 'user_pref("browser.dom.window.dump.enabled", true);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("extensions.update.enabled", false);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("extensions.update.autoUpdateDefault", false);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("app.update.enabled", false);\n' >> "$TBPROFILE/prefs.js"
    - wget -q https://www.enigmail.net/jsunit/jsunit-0.1.6.xpi
    - cd jsunit; unzip ../jsunit-0.1.6.xpi; cd ..
    - wget -q https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/60.0b10/linux-x86_64/en-US/thunderbird-60.0b10.tar.bz2
    - tar -xjvf thunderbird-60.0b10.tar.bz2
    - thunderbird --version
    - thunderbird/thunderbird --version
  script:
    - export TBPROFILE="$(pwd)/tb-test-profile"
    - export TMPDIR="$(pwd)/tmp"
    - export XAUTHORITY="$(pwd)/tmp/.Xauthority"
    - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
    - ./configure --enable-tests --with-tb-path=`printf '%s/thunderbird/thunderbird' "$(pwd)"` --with-tb-args="--profile $TBPROFILE"
    - make dirs xpi
    - cat config/autoconf.mk
    - ls $TBPROFILE
    - cat $TBPROFILE/prefs.js
    - cat $TBPROFILE/extensions/*
    - ls -l $(pwd)/package/tests/pinentry-auto
    - ls -l /bin/bash
    - JS_TEST=initialize.js xvfb-run -a -f "$XAUTHORITY" $(which make) unit
  artifacts:
    paths:
      - config
      - tmp
      - tb-test-profile
